services:
  mysql:
    image: mysql:8.0
    container_name: fpt1-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
