server:
  port: 8082

spring:
  application:
    name: expo-service
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

internal:
  token: ${INTERNAL_TOKEN}
