server:
  port: 8081

spring:
  application:
    name: identity-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    placeholders:
      superAdminEmail: ${SUPER_ADMIN_EMAIL:admin@team1.local}
      superAdminPasswordHash: ${SUPER_ADMIN_PASSWORD_HASH:}

jwt:
  access-token-expiration: 3600000
