CREATE DATABASE IF NOT EXISTS identity;
CREATE DATABASE IF NOT EXISTS expo;
CREATE DATABASE IF NOT EXISTS reservation;
CREATE DATABASE IF NOT EXISTS ticket;
CREATE DATABASE IF NOT EXISTS recommendation;